### ISSUE TITLE
Releases not up-to-date (0.0.3)

### ISSUE THREAD

**Issue by stylesen** [arteria/django-sessioninfo#2]
I am maintaining the Debian packages for django-hijack and django-compat - https://qa.debian.org/developer.php?login=stylesen@gmail.com 

Recently django-sessioninfo is added as a dependency for django-hijack in version 2.0.0, hence would like to package django-sessioninfo in Debian. It will be great if you could keep the releases up-to-date here - https://github.com/arteria/django-sessioninfo/releases 

The latest release as per git commits is 0.0.3 but there is no release tarball available for the same, the one that is available is for 0.0.2.

**Comment by jvamvas** [comment]
First of all, thank you @stylesen for maintaining the deb packages of our apps! We will give our best to keep the releases aligned in the future.

We now have released a new no-op version with the number `0.0.4`. Please let us know if the problem persists.

**Comment by stylesen** [comment]
@jvamvas thanks for the quick turn around. Looks like this should solve things for me. Will get back if I need anything else.

Closing this issue.
